// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: weather.proto
// Protobuf Java Version: 4.34.2

package com.example.iis.grpc.weather;

/**
 * Protobuf type {@code weather.CityWeather}
 */
@com.google.protobuf.Generated
public final class CityWeather extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:weather.CityWeather)
    CityWeatherOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 2,
      /* suffix= */ "",
      "CityWeather");
  }
  // Use CityWeather.newBuilder() to construct.
  private CityWeather(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CityWeather() {
    city_ = "";
    temperature_ = "";
    humidity_ = "";
    pressure_ = "";
    windDirection_ = "";
    windSpeed_ = "";
    weather_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.iis.grpc.weather.WeatherProto.internal_static_weather_CityWeather_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.example.iis.grpc.weather.WeatherProto.internal_static_weather_CityWeather_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.iis.grpc.weather.WeatherProto.internal_static_weather_CityWeather_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.iis.grpc.weather.CityWeather.class, com.example.iis.grpc.weather.CityWeather.Builder.class);
  }

  public static final int CITY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object city_ = "";
  /**
   * <pre>
   * GradIme
   * </pre>
   *
   * <code>string city = 1;</code>
   * @return The city.
   */
  @java.lang.Override
  public java.lang.String getCity() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * GradIme
   * </pre>
   *
   * <code>string city = 1;</code>
   * @return The bytes for city.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCityBytes() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object temperature_ = "";
  /**
   * <pre>
   * Temp (°C)
   * </pre>
   *
   * <code>string temperature = 2;</code>
   * @return The temperature.
   */
  @java.lang.Override
  public java.lang.String getTemperature() {
    java.lang.Object ref = temperature_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      temperature_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Temp (°C)
   * </pre>
   *
   * <code>string temperature = 2;</code>
   * @return The bytes for temperature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTemperatureBytes() {
    java.lang.Object ref = temperature_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      temperature_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HUMIDITY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object humidity_ = "";
  /**
   * <pre>
   * Vlaga (%)
   * </pre>
   *
   * <code>string humidity = 3;</code>
   * @return The humidity.
   */
  @java.lang.Override
  public java.lang.String getHumidity() {
    java.lang.Object ref = humidity_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      humidity_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Vlaga (%)
   * </pre>
   *
   * <code>string humidity = 3;</code>
   * @return The bytes for humidity.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHumidityBytes() {
    java.lang.Object ref = humidity_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      humidity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRESSURE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pressure_ = "";
  /**
   * <pre>
   * Tlak (hPa)
   * </pre>
   *
   * <code>string pressure = 4;</code>
   * @return The pressure.
   */
  @java.lang.Override
  public java.lang.String getPressure() {
    java.lang.Object ref = pressure_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pressure_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Tlak (hPa)
   * </pre>
   *
   * <code>string pressure = 4;</code>
   * @return The bytes for pressure.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPressureBytes() {
    java.lang.Object ref = pressure_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pressure_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WIND_DIRECTION_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object windDirection_ = "";
  /**
   * <pre>
   * VjetarSmjer
   * </pre>
   *
   * <code>string wind_direction = 5;</code>
   * @return The windDirection.
   */
  @java.lang.Override
  public java.lang.String getWindDirection() {
    java.lang.Object ref = windDirection_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      windDirection_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * VjetarSmjer
   * </pre>
   *
   * <code>string wind_direction = 5;</code>
   * @return The bytes for windDirection.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWindDirectionBytes() {
    java.lang.Object ref = windDirection_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      windDirection_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WIND_SPEED_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object windSpeed_ = "";
  /**
   * <pre>
   * VjetarBrzina (m/s)
   * </pre>
   *
   * <code>string wind_speed = 6;</code>
   * @return The windSpeed.
   */
  @java.lang.Override
  public java.lang.String getWindSpeed() {
    java.lang.Object ref = windSpeed_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      windSpeed_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * VjetarBrzina (m/s)
   * </pre>
   *
   * <code>string wind_speed = 6;</code>
   * @return The bytes for windSpeed.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWindSpeedBytes() {
    java.lang.Object ref = windSpeed_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      windSpeed_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEATHER_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object weather_ = "";
  /**
   * <pre>
   * Vrijeme (textual description)
   * </pre>
   *
   * <code>string weather = 7;</code>
   * @return The weather.
   */
  @java.lang.Override
  public java.lang.String getWeather() {
    java.lang.Object ref = weather_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      weather_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Vrijeme (textual description)
   * </pre>
   *
   * <code>string weather = 7;</code>
   * @return The bytes for weather.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWeatherBytes() {
    java.lang.Object ref = weather_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      weather_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(city_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, city_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(temperature_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, temperature_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(humidity_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, humidity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pressure_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, pressure_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(windDirection_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, windDirection_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(windSpeed_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, windSpeed_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(weather_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, weather_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(city_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, city_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(temperature_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, temperature_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(humidity_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, humidity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pressure_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, pressure_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(windDirection_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, windDirection_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(windSpeed_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, windSpeed_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(weather_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, weather_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.iis.grpc.weather.CityWeather)) {
      return super.equals(obj);
    }
    com.example.iis.grpc.weather.CityWeather other = (com.example.iis.grpc.weather.CityWeather) obj;

    if (!getCity()
        .equals(other.getCity())) return false;
    if (!getTemperature()
        .equals(other.getTemperature())) return false;
    if (!getHumidity()
        .equals(other.getHumidity())) return false;
    if (!getPressure()
        .equals(other.getPressure())) return false;
    if (!getWindDirection()
        .equals(other.getWindDirection())) return false;
    if (!getWindSpeed()
        .equals(other.getWindSpeed())) return false;
    if (!getWeather()
        .equals(other.getWeather())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + getTemperature().hashCode();
    hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + getHumidity().hashCode();
    hash = (37 * hash) + PRESSURE_FIELD_NUMBER;
    hash = (53 * hash) + getPressure().hashCode();
    hash = (37 * hash) + WIND_DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + getWindDirection().hashCode();
    hash = (37 * hash) + WIND_SPEED_FIELD_NUMBER;
    hash = (53 * hash) + getWindSpeed().hashCode();
    hash = (37 * hash) + WEATHER_FIELD_NUMBER;
    hash = (53 * hash) + getWeather().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.iis.grpc.weather.CityWeather parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.iis.grpc.weather.CityWeather parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.iis.grpc.weather.CityWeather parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.iis.grpc.weather.CityWeather parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.iis.grpc.weather.CityWeather parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.iis.grpc.weather.CityWeather parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.iis.grpc.weather.CityWeather parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.iis.grpc.weather.CityWeather parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.iis.grpc.weather.CityWeather parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.iis.grpc.weather.CityWeather parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.iis.grpc.weather.CityWeather parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.iis.grpc.weather.CityWeather parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.iis.grpc.weather.CityWeather prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code weather.CityWeather}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:weather.CityWeather)
      com.example.iis.grpc.weather.CityWeatherOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.iis.grpc.weather.WeatherProto.internal_static_weather_CityWeather_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.iis.grpc.weather.WeatherProto.internal_static_weather_CityWeather_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.iis.grpc.weather.CityWeather.class, com.example.iis.grpc.weather.CityWeather.Builder.class);
    }

    // Construct using com.example.iis.grpc.weather.CityWeather.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      city_ = "";
      temperature_ = "";
      humidity_ = "";
      pressure_ = "";
      windDirection_ = "";
      windSpeed_ = "";
      weather_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.iis.grpc.weather.WeatherProto.internal_static_weather_CityWeather_descriptor;
    }

    @java.lang.Override
    public com.example.iis.grpc.weather.CityWeather getDefaultInstanceForType() {
      return com.example.iis.grpc.weather.CityWeather.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.iis.grpc.weather.CityWeather build() {
      com.example.iis.grpc.weather.CityWeather result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.iis.grpc.weather.CityWeather buildPartial() {
      com.example.iis.grpc.weather.CityWeather result = new com.example.iis.grpc.weather.CityWeather(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.iis.grpc.weather.CityWeather result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.city_ = city_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.temperature_ = temperature_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.humidity_ = humidity_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.pressure_ = pressure_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.windDirection_ = windDirection_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.windSpeed_ = windSpeed_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.weather_ = weather_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.iis.grpc.weather.CityWeather) {
        return mergeFrom((com.example.iis.grpc.weather.CityWeather)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.iis.grpc.weather.CityWeather other) {
      if (other == com.example.iis.grpc.weather.CityWeather.getDefaultInstance()) return this;
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTemperature().isEmpty()) {
        temperature_ = other.temperature_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getHumidity().isEmpty()) {
        humidity_ = other.humidity_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getPressure().isEmpty()) {
        pressure_ = other.pressure_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getWindDirection().isEmpty()) {
        windDirection_ = other.windDirection_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getWindSpeed().isEmpty()) {
        windSpeed_ = other.windSpeed_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getWeather().isEmpty()) {
        weather_ = other.weather_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              city_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              temperature_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              humidity_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              pressure_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              windDirection_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              windSpeed_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              weather_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object city_ = "";
    /**
     * <pre>
     * GradIme
     * </pre>
     *
     * <code>string city = 1;</code>
     * @return The city.
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * GradIme
     * </pre>
     *
     * <code>string city = 1;</code>
     * @return The bytes for city.
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * GradIme
     * </pre>
     *
     * <code>string city = 1;</code>
     * @param value The city to set.
     * @return This builder for chaining.
     */
    public Builder setCity(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      city_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * GradIme
     * </pre>
     *
     * <code>string city = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCity() {
      city_ = getDefaultInstance().getCity();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * GradIme
     * </pre>
     *
     * <code>string city = 1;</code>
     * @param value The bytes for city to set.
     * @return This builder for chaining.
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      city_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object temperature_ = "";
    /**
     * <pre>
     * Temp (°C)
     * </pre>
     *
     * <code>string temperature = 2;</code>
     * @return The temperature.
     */
    public java.lang.String getTemperature() {
      java.lang.Object ref = temperature_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        temperature_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Temp (°C)
     * </pre>
     *
     * <code>string temperature = 2;</code>
     * @return The bytes for temperature.
     */
    public com.google.protobuf.ByteString
        getTemperatureBytes() {
      java.lang.Object ref = temperature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        temperature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Temp (°C)
     * </pre>
     *
     * <code>string temperature = 2;</code>
     * @param value The temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperature(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      temperature_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Temp (°C)
     * </pre>
     *
     * <code>string temperature = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperature() {
      temperature_ = getDefaultInstance().getTemperature();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Temp (°C)
     * </pre>
     *
     * <code>string temperature = 2;</code>
     * @param value The bytes for temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperatureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      temperature_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object humidity_ = "";
    /**
     * <pre>
     * Vlaga (%)
     * </pre>
     *
     * <code>string humidity = 3;</code>
     * @return The humidity.
     */
    public java.lang.String getHumidity() {
      java.lang.Object ref = humidity_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        humidity_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Vlaga (%)
     * </pre>
     *
     * <code>string humidity = 3;</code>
     * @return The bytes for humidity.
     */
    public com.google.protobuf.ByteString
        getHumidityBytes() {
      java.lang.Object ref = humidity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        humidity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Vlaga (%)
     * </pre>
     *
     * <code>string humidity = 3;</code>
     * @param value The humidity to set.
     * @return This builder for chaining.
     */
    public Builder setHumidity(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      humidity_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vlaga (%)
     * </pre>
     *
     * <code>string humidity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHumidity() {
      humidity_ = getDefaultInstance().getHumidity();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vlaga (%)
     * </pre>
     *
     * <code>string humidity = 3;</code>
     * @param value The bytes for humidity to set.
     * @return This builder for chaining.
     */
    public Builder setHumidityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      humidity_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object pressure_ = "";
    /**
     * <pre>
     * Tlak (hPa)
     * </pre>
     *
     * <code>string pressure = 4;</code>
     * @return The pressure.
     */
    public java.lang.String getPressure() {
      java.lang.Object ref = pressure_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pressure_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Tlak (hPa)
     * </pre>
     *
     * <code>string pressure = 4;</code>
     * @return The bytes for pressure.
     */
    public com.google.protobuf.ByteString
        getPressureBytes() {
      java.lang.Object ref = pressure_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pressure_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Tlak (hPa)
     * </pre>
     *
     * <code>string pressure = 4;</code>
     * @param value The pressure to set.
     * @return This builder for chaining.
     */
    public Builder setPressure(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pressure_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tlak (hPa)
     * </pre>
     *
     * <code>string pressure = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPressure() {
      pressure_ = getDefaultInstance().getPressure();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tlak (hPa)
     * </pre>
     *
     * <code>string pressure = 4;</code>
     * @param value The bytes for pressure to set.
     * @return This builder for chaining.
     */
    public Builder setPressureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pressure_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object windDirection_ = "";
    /**
     * <pre>
     * VjetarSmjer
     * </pre>
     *
     * <code>string wind_direction = 5;</code>
     * @return The windDirection.
     */
    public java.lang.String getWindDirection() {
      java.lang.Object ref = windDirection_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        windDirection_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * VjetarSmjer
     * </pre>
     *
     * <code>string wind_direction = 5;</code>
     * @return The bytes for windDirection.
     */
    public com.google.protobuf.ByteString
        getWindDirectionBytes() {
      java.lang.Object ref = windDirection_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        windDirection_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * VjetarSmjer
     * </pre>
     *
     * <code>string wind_direction = 5;</code>
     * @param value The windDirection to set.
     * @return This builder for chaining.
     */
    public Builder setWindDirection(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      windDirection_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * VjetarSmjer
     * </pre>
     *
     * <code>string wind_direction = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearWindDirection() {
      windDirection_ = getDefaultInstance().getWindDirection();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * VjetarSmjer
     * </pre>
     *
     * <code>string wind_direction = 5;</code>
     * @param value The bytes for windDirection to set.
     * @return This builder for chaining.
     */
    public Builder setWindDirectionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      windDirection_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object windSpeed_ = "";
    /**
     * <pre>
     * VjetarBrzina (m/s)
     * </pre>
     *
     * <code>string wind_speed = 6;</code>
     * @return The windSpeed.
     */
    public java.lang.String getWindSpeed() {
      java.lang.Object ref = windSpeed_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        windSpeed_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * VjetarBrzina (m/s)
     * </pre>
     *
     * <code>string wind_speed = 6;</code>
     * @return The bytes for windSpeed.
     */
    public com.google.protobuf.ByteString
        getWindSpeedBytes() {
      java.lang.Object ref = windSpeed_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        windSpeed_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * VjetarBrzina (m/s)
     * </pre>
     *
     * <code>string wind_speed = 6;</code>
     * @param value The windSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setWindSpeed(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      windSpeed_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * VjetarBrzina (m/s)
     * </pre>
     *
     * <code>string wind_speed = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearWindSpeed() {
      windSpeed_ = getDefaultInstance().getWindSpeed();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * VjetarBrzina (m/s)
     * </pre>
     *
     * <code>string wind_speed = 6;</code>
     * @param value The bytes for windSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setWindSpeedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      windSpeed_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object weather_ = "";
    /**
     * <pre>
     * Vrijeme (textual description)
     * </pre>
     *
     * <code>string weather = 7;</code>
     * @return The weather.
     */
    public java.lang.String getWeather() {
      java.lang.Object ref = weather_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weather_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Vrijeme (textual description)
     * </pre>
     *
     * <code>string weather = 7;</code>
     * @return The bytes for weather.
     */
    public com.google.protobuf.ByteString
        getWeatherBytes() {
      java.lang.Object ref = weather_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weather_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Vrijeme (textual description)
     * </pre>
     *
     * <code>string weather = 7;</code>
     * @param value The weather to set.
     * @return This builder for chaining.
     */
    public Builder setWeather(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      weather_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vrijeme (textual description)
     * </pre>
     *
     * <code>string weather = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeather() {
      weather_ = getDefaultInstance().getWeather();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vrijeme (textual description)
     * </pre>
     *
     * <code>string weather = 7;</code>
     * @param value The bytes for weather to set.
     * @return This builder for chaining.
     */
    public Builder setWeatherBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      weather_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:weather.CityWeather)
  }

  // @@protoc_insertion_point(class_scope:weather.CityWeather)
  private static final com.example.iis.grpc.weather.CityWeather DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.iis.grpc.weather.CityWeather();
  }

  public static com.example.iis.grpc.weather.CityWeather getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CityWeather>
      PARSER = new com.google.protobuf.AbstractParser<CityWeather>() {
    @java.lang.Override
    public CityWeather parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CityWeather> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CityWeather> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.iis.grpc.weather.CityWeather getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

