// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: weather.proto
// Protobuf Java Version: 4.34.2

package com.example.iis.grpc.weather;

@com.google.protobuf.Generated
public interface CityWeatherOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weather.CityWeather)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * GradIme
   * </pre>
   *
   * <code>string city = 1;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <pre>
   * GradIme
   * </pre>
   *
   * <code>string city = 1;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <pre>
   * Temp (°C)
   * </pre>
   *
   * <code>string temperature = 2;</code>
   * @return The temperature.
   */
  java.lang.String getTemperature();
  /**
   * <pre>
   * Temp (°C)
   * </pre>
   *
   * <code>string temperature = 2;</code>
   * @return The bytes for temperature.
   */
  com.google.protobuf.ByteString
      getTemperatureBytes();

  /**
   * <pre>
   * Vlaga (%)
   * </pre>
   *
   * <code>string humidity = 3;</code>
   * @return The humidity.
   */
  java.lang.String getHumidity();
  /**
   * <pre>
   * Vlaga (%)
   * </pre>
   *
   * <code>string humidity = 3;</code>
   * @return The bytes for humidity.
   */
  com.google.protobuf.ByteString
      getHumidityBytes();

  /**
   * <pre>
   * Tlak (hPa)
   * </pre>
   *
   * <code>string pressure = 4;</code>
   * @return The pressure.
   */
  java.lang.String getPressure();
  /**
   * <pre>
   * Tlak (hPa)
   * </pre>
   *
   * <code>string pressure = 4;</code>
   * @return The bytes for pressure.
   */
  com.google.protobuf.ByteString
      getPressureBytes();

  /**
   * <pre>
   * VjetarSmjer
   * </pre>
   *
   * <code>string wind_direction = 5;</code>
   * @return The windDirection.
   */
  java.lang.String getWindDirection();
  /**
   * <pre>
   * VjetarSmjer
   * </pre>
   *
   * <code>string wind_direction = 5;</code>
   * @return The bytes for windDirection.
   */
  com.google.protobuf.ByteString
      getWindDirectionBytes();

  /**
   * <pre>
   * VjetarBrzina (m/s)
   * </pre>
   *
   * <code>string wind_speed = 6;</code>
   * @return The windSpeed.
   */
  java.lang.String getWindSpeed();
  /**
   * <pre>
   * VjetarBrzina (m/s)
   * </pre>
   *
   * <code>string wind_speed = 6;</code>
   * @return The bytes for windSpeed.
   */
  com.google.protobuf.ByteString
      getWindSpeedBytes();

  /**
   * <pre>
   * Vrijeme (textual description)
   * </pre>
   *
   * <code>string weather = 7;</code>
   * @return The weather.
   */
  java.lang.String getWeather();
  /**
   * <pre>
   * Vrijeme (textual description)
   * </pre>
   *
   * <code>string weather = 7;</code>
   * @return The bytes for weather.
   */
  com.google.protobuf.ByteString
      getWeatherBytes();
}
