// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: weather.proto
// Protobuf Java Version: 4.34.2

package com.example.iis.grpc.weather;

@com.google.protobuf.Generated
public interface TemperatureReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weather.TemperatureReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .weather.CityWeather results = 1;</code>
   */
  java.util.List<com.example.iis.grpc.weather.CityWeather> 
      getResultsList();
  /**
   * <code>repeated .weather.CityWeather results = 1;</code>
   */
  com.example.iis.grpc.weather.CityWeather getResults(int index);
  /**
   * <code>repeated .weather.CityWeather results = 1;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .weather.CityWeather results = 1;</code>
   */
  java.util.List<? extends com.example.iis.grpc.weather.CityWeatherOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .weather.CityWeather results = 1;</code>
   */
  com.example.iis.grpc.weather.CityWeatherOrBuilder getResultsOrBuilder(
      int index);

  /**
   * <pre>
   * Timestamp of the DHMZ measurement (date + term/hour).
   * </pre>
   *
   * <code>string measured_at = 2;</code>
   * @return The measuredAt.
   */
  java.lang.String getMeasuredAt();
  /**
   * <pre>
   * Timestamp of the DHMZ measurement (date + term/hour).
   * </pre>
   *
   * <code>string measured_at = 2;</code>
   * @return The bytes for measuredAt.
   */
  com.google.protobuf.ByteString
      getMeasuredAtBytes();
}
