// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: weather.proto
// Protobuf Java Version: 4.34.2

package com.example.iis.grpc.weather;

@com.google.protobuf.Generated
public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weather.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * City name or part of a city name (e.g. "zag", "split", "osij").
   * </pre>
   *
   * <code>string query = 1;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <pre>
   * City name or part of a city name (e.g. "zag", "split", "osij").
   * </pre>
   *
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();
}
