// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: weather.proto
// Protobuf Java Version: 4.34.2

package com.example.iis.grpc.weather;

/**
 * Protobuf type {@code weather.TemperatureReply}
 */
@com.google.protobuf.Generated
public final class TemperatureReply extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:weather.TemperatureReply)
    TemperatureReplyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 2,
      /* suffix= */ "",
      "TemperatureReply");
  }
  // Use TemperatureReply.newBuilder() to construct.
  private TemperatureReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TemperatureReply() {
    results_ = java.util.Collections.emptyList();
    measuredAt_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.iis.grpc.weather.WeatherProto.internal_static_weather_TemperatureReply_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.example.iis.grpc.weather.WeatherProto.internal_static_weather_TemperatureReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.iis.grpc.weather.WeatherProto.internal_static_weather_TemperatureReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.iis.grpc.weather.TemperatureReply.class, com.example.iis.grpc.weather.TemperatureReply.Builder.class);
  }

  public static final int RESULTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.example.iis.grpc.weather.CityWeather> results_;
  /**
   * <code>repeated .weather.CityWeather results = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.iis.grpc.weather.CityWeather> getResultsList() {
    return results_;
  }
  /**
   * <code>repeated .weather.CityWeather results = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.iis.grpc.weather.CityWeatherOrBuilder> 
      getResultsOrBuilderList() {
    return results_;
  }
  /**
   * <code>repeated .weather.CityWeather results = 1;</code>
   */
  @java.lang.Override
  public int getResultsCount() {
    return results_.size();
  }
  /**
   * <code>repeated .weather.CityWeather results = 1;</code>
   */
  @java.lang.Override
  public com.example.iis.grpc.weather.CityWeather getResults(int index) {
    return results_.get(index);
  }
  /**
   * <code>repeated .weather.CityWeather results = 1;</code>
   */
  @java.lang.Override
  public com.example.iis.grpc.weather.CityWeatherOrBuilder getResultsOrBuilder(
      int index) {
    return results_.get(index);
  }

  public static final int MEASURED_AT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object measuredAt_ = "";
  /**
   * <pre>
   * Timestamp of the DHMZ measurement (date + term/hour).
   * </pre>
   *
   * <code>string measured_at = 2;</code>
   * @return The measuredAt.
   */
  @java.lang.Override
  public java.lang.String getMeasuredAt() {
    java.lang.Object ref = measuredAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      measuredAt_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Timestamp of the DHMZ measurement (date + term/hour).
   * </pre>
   *
   * <code>string measured_at = 2;</code>
   * @return The bytes for measuredAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMeasuredAtBytes() {
    java.lang.Object ref = measuredAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      measuredAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < results_.size(); i++) {
      output.writeMessage(1, results_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(measuredAt_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, measuredAt_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;

        {
          final int count = results_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(results_.get(i));
          }
          size += 1 * count;
        }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(measuredAt_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, measuredAt_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.iis.grpc.weather.TemperatureReply)) {
      return super.equals(obj);
    }
    com.example.iis.grpc.weather.TemperatureReply other = (com.example.iis.grpc.weather.TemperatureReply) obj;

    if (!getResultsList()
        .equals(other.getResultsList())) return false;
    if (!getMeasuredAt()
        .equals(other.getMeasuredAt())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResultsCount() > 0) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getResultsList().hashCode();
    }
    hash = (37 * hash) + MEASURED_AT_FIELD_NUMBER;
    hash = (53 * hash) + getMeasuredAt().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.iis.grpc.weather.TemperatureReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.iis.grpc.weather.TemperatureReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.iis.grpc.weather.TemperatureReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.iis.grpc.weather.TemperatureReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.iis.grpc.weather.TemperatureReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.iis.grpc.weather.TemperatureReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.iis.grpc.weather.TemperatureReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.iis.grpc.weather.TemperatureReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.iis.grpc.weather.TemperatureReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.iis.grpc.weather.TemperatureReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.iis.grpc.weather.TemperatureReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.iis.grpc.weather.TemperatureReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.iis.grpc.weather.TemperatureReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code weather.TemperatureReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:weather.TemperatureReply)
      com.example.iis.grpc.weather.TemperatureReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.iis.grpc.weather.WeatherProto.internal_static_weather_TemperatureReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.iis.grpc.weather.WeatherProto.internal_static_weather_TemperatureReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.iis.grpc.weather.TemperatureReply.class, com.example.iis.grpc.weather.TemperatureReply.Builder.class);
    }

    // Construct using com.example.iis.grpc.weather.TemperatureReply.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
      } else {
        results_ = null;
        resultsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      measuredAt_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.iis.grpc.weather.WeatherProto.internal_static_weather_TemperatureReply_descriptor;
    }

    @java.lang.Override
    public com.example.iis.grpc.weather.TemperatureReply getDefaultInstanceForType() {
      return com.example.iis.grpc.weather.TemperatureReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.iis.grpc.weather.TemperatureReply build() {
      com.example.iis.grpc.weather.TemperatureReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.iis.grpc.weather.TemperatureReply buildPartial() {
      com.example.iis.grpc.weather.TemperatureReply result = new com.example.iis.grpc.weather.TemperatureReply(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.iis.grpc.weather.TemperatureReply result) {
      if (resultsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          results_ = java.util.Collections.unmodifiableList(results_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.results_ = results_;
      } else {
        result.results_ = resultsBuilder_.build();
      }
    }

    private void buildPartial0(com.example.iis.grpc.weather.TemperatureReply result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.measuredAt_ = measuredAt_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.iis.grpc.weather.TemperatureReply) {
        return mergeFrom((com.example.iis.grpc.weather.TemperatureReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.iis.grpc.weather.TemperatureReply other) {
      if (other == com.example.iis.grpc.weather.TemperatureReply.getDefaultInstance()) return this;
      if (resultsBuilder_ == null) {
        if (!other.results_.isEmpty()) {
          if (results_.isEmpty()) {
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultsIsMutable();
            results_.addAll(other.results_);
          }
          onChanged();
        }
      } else {
        if (!other.results_.isEmpty()) {
          if (resultsBuilder_.isEmpty()) {
            resultsBuilder_.dispose();
            resultsBuilder_ = null;
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000001);
            resultsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetResultsFieldBuilder() : null;
          } else {
            resultsBuilder_.addAllMessages(other.results_);
          }
        }
      }
      if (!other.getMeasuredAt().isEmpty()) {
        measuredAt_ = other.measuredAt_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.example.iis.grpc.weather.CityWeather m =
                  input.readMessage(
                      com.example.iis.grpc.weather.CityWeather.parser(),
                      extensionRegistry);
              if (resultsBuilder_ == null) {
                ensureResultsIsMutable();
                results_.add(m);
              } else {
                resultsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              measuredAt_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.iis.grpc.weather.CityWeather> results_ =
      java.util.Collections.emptyList();
    private void ensureResultsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        results_ = new java.util.ArrayList<com.example.iis.grpc.weather.CityWeather>(results_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.example.iis.grpc.weather.CityWeather, com.example.iis.grpc.weather.CityWeather.Builder, com.example.iis.grpc.weather.CityWeatherOrBuilder> resultsBuilder_;

    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public java.util.List<com.example.iis.grpc.weather.CityWeather> getResultsList() {
      if (resultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(results_);
      } else {
        return resultsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public int getResultsCount() {
      if (resultsBuilder_ == null) {
        return results_.size();
      } else {
        return resultsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public com.example.iis.grpc.weather.CityWeather getResults(int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);
      } else {
        return resultsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public Builder setResults(
        int index, com.example.iis.grpc.weather.CityWeather value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.set(index, value);
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public Builder setResults(
        int index, com.example.iis.grpc.weather.CityWeather.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public Builder addResults(com.example.iis.grpc.weather.CityWeather value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public Builder addResults(
        int index, com.example.iis.grpc.weather.CityWeather value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(index, value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public Builder addResults(
        com.example.iis.grpc.weather.CityWeather.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public Builder addResults(
        int index, com.example.iis.grpc.weather.CityWeather.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public Builder addAllResults(
        java.lang.Iterable<? extends com.example.iis.grpc.weather.CityWeather> values) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, results_);
        onChanged();
      } else {
        resultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public Builder clearResults() {
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public Builder removeResults(int index) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.remove(index);
        onChanged();
      } else {
        resultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public com.example.iis.grpc.weather.CityWeather.Builder getResultsBuilder(
        int index) {
      return internalGetResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public com.example.iis.grpc.weather.CityWeatherOrBuilder getResultsOrBuilder(
        int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);  } else {
        return resultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public java.util.List<? extends com.example.iis.grpc.weather.CityWeatherOrBuilder> 
         getResultsOrBuilderList() {
      if (resultsBuilder_ != null) {
        return resultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(results_);
      }
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public com.example.iis.grpc.weather.CityWeather.Builder addResultsBuilder() {
      return internalGetResultsFieldBuilder().addBuilder(
          com.example.iis.grpc.weather.CityWeather.getDefaultInstance());
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public com.example.iis.grpc.weather.CityWeather.Builder addResultsBuilder(
        int index) {
      return internalGetResultsFieldBuilder().addBuilder(
          index, com.example.iis.grpc.weather.CityWeather.getDefaultInstance());
    }
    /**
     * <code>repeated .weather.CityWeather results = 1;</code>
     */
    public java.util.List<com.example.iis.grpc.weather.CityWeather.Builder> 
         getResultsBuilderList() {
      return internalGetResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.example.iis.grpc.weather.CityWeather, com.example.iis.grpc.weather.CityWeather.Builder, com.example.iis.grpc.weather.CityWeatherOrBuilder> 
        internalGetResultsFieldBuilder() {
      if (resultsBuilder_ == null) {
        resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.example.iis.grpc.weather.CityWeather, com.example.iis.grpc.weather.CityWeather.Builder, com.example.iis.grpc.weather.CityWeatherOrBuilder>(
                results_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        results_ = null;
      }
      return resultsBuilder_;
    }

    private java.lang.Object measuredAt_ = "";
    /**
     * <pre>
     * Timestamp of the DHMZ measurement (date + term/hour).
     * </pre>
     *
     * <code>string measured_at = 2;</code>
     * @return The measuredAt.
     */
    public java.lang.String getMeasuredAt() {
      java.lang.Object ref = measuredAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        measuredAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Timestamp of the DHMZ measurement (date + term/hour).
     * </pre>
     *
     * <code>string measured_at = 2;</code>
     * @return The bytes for measuredAt.
     */
    public com.google.protobuf.ByteString
        getMeasuredAtBytes() {
      java.lang.Object ref = measuredAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        measuredAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Timestamp of the DHMZ measurement (date + term/hour).
     * </pre>
     *
     * <code>string measured_at = 2;</code>
     * @param value The measuredAt to set.
     * @return This builder for chaining.
     */
    public Builder setMeasuredAt(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      measuredAt_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp of the DHMZ measurement (date + term/hour).
     * </pre>
     *
     * <code>string measured_at = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMeasuredAt() {
      measuredAt_ = getDefaultInstance().getMeasuredAt();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp of the DHMZ measurement (date + term/hour).
     * </pre>
     *
     * <code>string measured_at = 2;</code>
     * @param value The bytes for measuredAt to set.
     * @return This builder for chaining.
     */
    public Builder setMeasuredAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      measuredAt_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:weather.TemperatureReply)
  }

  // @@protoc_insertion_point(class_scope:weather.TemperatureReply)
  private static final com.example.iis.grpc.weather.TemperatureReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.iis.grpc.weather.TemperatureReply();
  }

  public static com.example.iis.grpc.weather.TemperatureReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TemperatureReply>
      PARSER = new com.google.protobuf.AbstractParser<TemperatureReply>() {
    @java.lang.Override
    public TemperatureReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TemperatureReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TemperatureReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.iis.grpc.weather.TemperatureReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

