// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: weather.proto
// Protobuf Java Version: 4.34.2

package com.example.iis.grpc.weather;

@com.google.protobuf.Generated
public final class WeatherProto extends com.google.protobuf.GeneratedFile {
  private WeatherProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 2,
      /* suffix= */ "",
      "WeatherProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weather_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_weather_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weather_TemperatureReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_weather_TemperatureReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weather_CityWeather_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_weather_CityWeather_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rweather.proto\022\007weather\"#\n\022TemperatureR" +
      "equest\022\r\n\005query\030\001 \001(\t\"N\n\020TemperatureRepl" +
      "y\022%\n\007results\030\001 \003(\0132\024.weather.CityWeather" +
      "\022\023\n\013measured_at\030\002 \001(\t\"\221\001\n\013CityWeather\022\014\n" +
      "\004city\030\001 \001(\t\022\023\n\013temperature\030\002 \001(\t\022\020\n\010humi" +
      "dity\030\003 \001(\t\022\020\n\010pressure\030\004 \001(\t\022\026\n\016wind_dir" +
      "ection\030\005 \001(\t\022\022\n\nwind_speed\030\006 \001(\t\022\017\n\007weat" +
      "her\030\007 \001(\t2Z\n\016WeatherService\022H\n\016GetTemper" +
      "ature\022\033.weather.TemperatureRequest\032\031.wea" +
      "ther.TemperatureReplyB.\n\034com.example.iis" +
      ".grpc.weatherB\014WeatherProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_weather_TemperatureRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_weather_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_weather_TemperatureRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_weather_TemperatureReply_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_weather_TemperatureReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_weather_TemperatureReply_descriptor,
        new java.lang.String[] { "Results", "MeasuredAt", });
    internal_static_weather_CityWeather_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_weather_CityWeather_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_weather_CityWeather_descriptor,
        new java.lang.String[] { "City", "Temperature", "Humidity", "Pressure", "WindDirection", "WindSpeed", "Weather", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
