spring.application.name=iis-backend
server.port=8080

spring.datasource.url=jdbc:h2:mem:iis;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.jwt.secret=Y2hhbmdlLW1lLXRoaXMtaXMtYS1kZW1vLXNlY3JldC1mb3ItaWlzLXByb2plY3QtMTIzNDU2Nzg=
app.jwt.access-token-ttl-minutes=15
app.jwt.refresh-token-ttl-days=7

#app.order-source=woocommerce
app.order-source=custom

app.woocommerce.base-url=http://localhost:8090
app.woocommerce.consumer-key=ck_e253746a9cf1acf60129f2cebb8211967a9a9f9f
app.woocommerce.consumer-secret=cs_62e5964eb27badcae8422f612ff5524e1eae319e

app.grpc.port=9090

app.dhmz.url=https://vrijeme.hr/hrvatska_n.xml

app.xml.orders-file=data/orders-data.xml

spring.graphql.graphiql.enabled=true
spring.graphql.schema.printer.enabled=true

logging.level.com.example.iis=INFO
